#define ROOM_WIDTH 16
#define ROOM_HEIGHT 4

#define NUM_SIDES 4

#define RAND_LIMIT 2

#define RENDER_DEPTH 10

#define WORLD_CACHE_LENGTH 100

#define MOUSE_SENSITIVITY 0.1f

#define ACCELERATION 100
#define WALL_ACCELERATION_FACTOR 1.2f

#define PLAYER_HEIGHT 2.0f

#define FRICTION 8
#define AERIAL_FRICTION 4
#define WALL_FRICTION 30

#define GRAVITY 35

#define JUMP_VELOCITY 10

#define WALL_PADDING 1
